name: Release

on:
  release:
    types: [published]

jobs:

  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'
        fetch-depth: 0
      id: go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        workdir: .
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

    - name: Upload assets
      uses: actions/upload-artifact@v3
      with:
        name: traefik-forward-auth
        path: ./dist/*